// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account.sql

package db

import (
	"context"
	"database/sql"
)

const clearAccountPrimaryWallet = `-- name: ClearAccountPrimaryWallet :exec
UPDATE accounts
SET primary_wallet_id = NULL, updated_at = NOW()
WHERE owner_id = ? AND account_type = 'USER' AND status != 'CLOSED'
`

// Primary 지갑 연결 해제
func (q *Queries) ClearAccountPrimaryWallet(ctx context.Context, ownerID sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, clearAccountPrimaryWallet, ownerID)
	return err
}

const countAccountsByType = `-- name: CountAccountsByType :one
SELECT COUNT(*) as total FROM accounts
WHERE account_type = ? AND status != 'CLOSED'
`

// 타입별 계정 수
func (q *Queries) CountAccountsByType(ctx context.Context, accountType AccountsAccountType) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAccountsByType, accountType)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createAccount = `-- name: CreateAccount :execresult

INSERT INTO accounts (account_type, owner_id, external_id, status)
VALUES (?, ?, ?, 'ACTIVE')
`

type CreateAccountParams struct {
	AccountType AccountsAccountType `json:"account_type"`
	OwnerID     sql.NullInt64       `json:"owner_id"`
	ExternalID  sql.NullString      `json:"external_id"`
}

// ============================================================================
// Account Queries - Phase 1
// ============================================================================
// NOTE: external_id는 서비스 레이어에서 UUID 생성 후 전달
// 계정 생성 (사용자 회원가입 시 자동 생성)
// account_type: USER(일반), MERCHANT(판매자), ESCROW(에스크로), SYSTEM(시스템)
func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createAccount, arg.AccountType, arg.OwnerID, arg.ExternalID)
}

const getAccountBalance = `-- name: GetAccountBalance :one

SELECT id, balance, hold_balance, version
FROM accounts
WHERE id = ? AND status != 'CLOSED'
`

type GetAccountBalanceRow struct {
	ID          uint64 `json:"id"`
	Balance     string `json:"balance"`
	HoldBalance string `json:"hold_balance"`
	Version     uint32 `json:"version"`
}

// ============================================================================
// 잔액 조회 (Phase 3+에서 사용, Phase 1에서는 미사용)
// ============================================================================
// 잔액 조회 (balance, hold_balance, version)
func (q *Queries) GetAccountBalance(ctx context.Context, id uint64) (GetAccountBalanceRow, error) {
	row := q.db.QueryRowContext(ctx, getAccountBalance, id)
	var i GetAccountBalanceRow
	err := row.Scan(
		&i.ID,
		&i.Balance,
		&i.HoldBalance,
		&i.Version,
	)
	return i, err
}

const getAccountByExternalID = `-- name: GetAccountByExternalID :one
SELECT id, account_type, owner_id, primary_wallet_id, external_id, balance, hold_balance, version, status, created_at, updated_at FROM accounts
WHERE external_id = ? AND status != 'CLOSED'
`

// 외부 식별자로 조회 (API 노출용)
func (q *Queries) GetAccountByExternalID(ctx context.Context, externalID sql.NullString) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByExternalID, externalID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.AccountType,
		&i.OwnerID,
		&i.PrimaryWalletID,
		&i.ExternalID,
		&i.Balance,
		&i.HoldBalance,
		&i.Version,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, account_type, owner_id, primary_wallet_id, external_id, balance, hold_balance, version, status, created_at, updated_at FROM accounts
WHERE id = ? AND status != 'CLOSED'
`

// ID로 계정 조회
func (q *Queries) GetAccountByID(ctx context.Context, id uint64) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.AccountType,
		&i.OwnerID,
		&i.PrimaryWalletID,
		&i.ExternalID,
		&i.Balance,
		&i.HoldBalance,
		&i.Version,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByOwnerForUpdate = `-- name: GetAccountByOwnerForUpdate :one
SELECT id, account_type, owner_id, primary_wallet_id, external_id, balance, hold_balance, version, status, created_at, updated_at FROM accounts
WHERE owner_id = ? AND account_type = 'USER' AND status != 'CLOSED'
FOR UPDATE
`

// 사용자 ID로 계정 조회 + row-lock
func (q *Queries) GetAccountByOwnerForUpdate(ctx context.Context, ownerID sql.NullInt64) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByOwnerForUpdate, ownerID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.AccountType,
		&i.OwnerID,
		&i.PrimaryWalletID,
		&i.ExternalID,
		&i.Balance,
		&i.HoldBalance,
		&i.Version,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByOwnerID = `-- name: GetAccountByOwnerID :one
SELECT id, account_type, owner_id, primary_wallet_id, external_id, balance, hold_balance, version, status, created_at, updated_at FROM accounts
WHERE owner_id = ? AND account_type = 'USER' AND status != 'CLOSED'
`

// 사용자 ID로 계정 조회 (1:1 관계 가정)
func (q *Queries) GetAccountByOwnerID(ctx context.Context, ownerID sql.NullInt64) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByOwnerID, ownerID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.AccountType,
		&i.OwnerID,
		&i.PrimaryWalletID,
		&i.ExternalID,
		&i.Balance,
		&i.HoldBalance,
		&i.Version,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountForUpdate = `-- name: GetAccountForUpdate :one
SELECT id, account_type, owner_id, primary_wallet_id, external_id, balance, hold_balance, version, status, created_at, updated_at FROM accounts
WHERE id = ? AND status != 'CLOSED'
FOR UPDATE
`

// 트랜잭션 내 row-lock (잔액 변경, Primary 지갑 연결 등)
func (q *Queries) GetAccountForUpdate(ctx context.Context, id uint64) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountForUpdate, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.AccountType,
		&i.OwnerID,
		&i.PrimaryWalletID,
		&i.ExternalID,
		&i.Balance,
		&i.HoldBalance,
		&i.Version,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccountsByType = `-- name: ListAccountsByType :many

SELECT id, account_type, owner_id, primary_wallet_id, external_id, balance, hold_balance, version, status, created_at, updated_at FROM accounts
WHERE account_type = ? AND status != 'CLOSED'
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListAccountsByTypeParams struct {
	AccountType AccountsAccountType `json:"account_type"`
	Limit       int32               `json:"limit"`
	Offset      int32               `json:"offset"`
}

// ============================================================================
// 목록 조회
// ============================================================================
// 타입별 계정 목록
func (q *Queries) ListAccountsByType(ctx context.Context, arg ListAccountsByTypeParams) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listAccountsByType, arg.AccountType, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.AccountType,
			&i.OwnerID,
			&i.PrimaryWalletID,
			&i.ExternalID,
			&i.Balance,
			&i.HoldBalance,
			&i.Version,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountPrimaryWallet = `-- name: UpdateAccountPrimaryWallet :exec

UPDATE accounts
SET primary_wallet_id = ?, updated_at = NOW()
WHERE owner_id = ? AND account_type = 'USER' AND status != 'CLOSED'
`

type UpdateAccountPrimaryWalletParams struct {
	PrimaryWalletID sql.NullInt64 `json:"primary_wallet_id"`
	OwnerID         sql.NullInt64 `json:"owner_id"`
}

// ============================================================================
// 계정 업데이트
// ============================================================================
// Primary 지갑 연결 (지갑 SetPrimary 후 호출)
func (q *Queries) UpdateAccountPrimaryWallet(ctx context.Context, arg UpdateAccountPrimaryWalletParams) error {
	_, err := q.db.ExecContext(ctx, updateAccountPrimaryWallet, arg.PrimaryWalletID, arg.OwnerID)
	return err
}

const updateAccountStatusToActive = `-- name: UpdateAccountStatusToActive :exec
UPDATE accounts
SET status = 'ACTIVE', updated_at = NOW()
WHERE id = ? AND status = 'SUSPENDED'
`

// 정지 해제 (SUSPENDED → ACTIVE)
func (q *Queries) UpdateAccountStatusToActive(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, updateAccountStatusToActive, id)
	return err
}

const updateAccountStatusToClosed = `-- name: UpdateAccountStatusToClosed :exec
UPDATE accounts
SET status = 'CLOSED', updated_at = NOW()
WHERE id = ? AND status != 'CLOSED'
`

// 계정 폐쇄 (사용자 탈퇴 시)
func (q *Queries) UpdateAccountStatusToClosed(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, updateAccountStatusToClosed, id)
	return err
}

const updateAccountStatusToSuspended = `-- name: UpdateAccountStatusToSuspended :exec

UPDATE accounts
SET status = 'SUSPENDED', updated_at = NOW()
WHERE id = ? AND status = 'ACTIVE'
`

// ============================================================================
// 계정 상태 변경
// ============================================================================
// 계정 정지 (ACTIVE → SUSPENDED)
func (q *Queries) UpdateAccountStatusToSuspended(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, updateAccountStatusToSuspended, id)
	return err
}
