// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account.sql

package db

import (
	"context"
	"database/sql"
)

const createAccount = `-- name: CreateAccount :execresult
INSERT INTO accounts (external_id, account_type, status)
VALUES (?, ?, ?)
`

type CreateAccountParams struct {
	ExternalID  string              `json:"external_id"`
	AccountType AccountsAccountType `json:"account_type"`
	Status      AccountsStatus      `json:"status"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createAccount, arg.ExternalID, arg.AccountType, arg.Status)
}

const createBalance = `-- name: CreateBalance :execresult
INSERT INTO balances (account_id, currency, available, held, version)
VALUES (?, ?, ?, ?, 0)
`

type CreateBalanceParams struct {
	AccountID uint64 `json:"account_id"`
	Currency  string `json:"currency"`
	Available string `json:"available"`
	Held      string `json:"held"`
}

func (q *Queries) CreateBalance(ctx context.Context, arg CreateBalanceParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createBalance,
		arg.AccountID,
		arg.Currency,
		arg.Available,
		arg.Held,
	)
}

const getAccount = `-- name: GetAccount :one
SELECT id, external_id, account_type, status, created_at, updated_at FROM accounts WHERE id = ? LIMIT 1
`

func (q *Queries) GetAccount(ctx context.Context, id uint64) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.AccountType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByExternalID = `-- name: GetAccountByExternalID :one
SELECT id, external_id, account_type, status, created_at, updated_at FROM accounts WHERE external_id = ? LIMIT 1
`

func (q *Queries) GetAccountByExternalID(ctx context.Context, externalID string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByExternalID, externalID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.AccountType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBalance = `-- name: GetBalance :one
SELECT id, account_id, currency, available, held, version, updated_at FROM balances WHERE account_id = ? AND currency = ? LIMIT 1
`

type GetBalanceParams struct {
	AccountID uint64 `json:"account_id"`
	Currency  string `json:"currency"`
}

func (q *Queries) GetBalance(ctx context.Context, arg GetBalanceParams) (Balance, error) {
	row := q.db.QueryRowContext(ctx, getBalance, arg.AccountID, arg.Currency)
	var i Balance
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Currency,
		&i.Available,
		&i.Held,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}

const getBalanceForUpdate = `-- name: GetBalanceForUpdate :one
SELECT id, account_id, currency, available, held, version, updated_at FROM balances WHERE account_id = ? AND currency = ? FOR UPDATE
`

type GetBalanceForUpdateParams struct {
	AccountID uint64 `json:"account_id"`
	Currency  string `json:"currency"`
}

func (q *Queries) GetBalanceForUpdate(ctx context.Context, arg GetBalanceForUpdateParams) (Balance, error) {
	row := q.db.QueryRowContext(ctx, getBalanceForUpdate, arg.AccountID, arg.Currency)
	var i Balance
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Currency,
		&i.Available,
		&i.Held,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccountsByType = `-- name: ListAccountsByType :many
SELECT id, external_id, account_type, status, created_at, updated_at FROM accounts WHERE account_type = ? AND status = 'ACTIVE'
`

func (q *Queries) ListAccountsByType(ctx context.Context, accountType AccountsAccountType) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listAccountsByType, accountType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.AccountType,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountStatus = `-- name: UpdateAccountStatus :exec
UPDATE accounts SET status = ? WHERE id = ?
`

type UpdateAccountStatusParams struct {
	Status AccountsStatus `json:"status"`
	ID     uint64         `json:"id"`
}

func (q *Queries) UpdateAccountStatus(ctx context.Context, arg UpdateAccountStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateAccountStatus, arg.Status, arg.ID)
	return err
}

const updateBalanceOptimistic = `-- name: UpdateBalanceOptimistic :execresult
UPDATE balances
SET available = ?, held = ?, version = version + 1
WHERE id = ? AND version = ?
`

type UpdateBalanceOptimisticParams struct {
	Available string `json:"available"`
	Held      string `json:"held"`
	ID        uint64 `json:"id"`
	Version   uint32 `json:"version"`
}

func (q *Queries) UpdateBalanceOptimistic(ctx context.Context, arg UpdateBalanceOptimisticParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateBalanceOptimistic,
		arg.Available,
		arg.Held,
		arg.ID,
		arg.Version,
	)
}
