// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deposit.sql

package db

import (
	"context"
	"database/sql"
)

const createDeposit = `-- name: CreateDeposit :execresult
INSERT INTO deposits (idempotency_key, account_id, amount, status)
VALUES (?, ?, ?, 'PENDING_MINT')
`

type CreateDepositParams struct {
	IdempotencyKey string `json:"idempotency_key"`
	AccountID      uint64 `json:"account_id"`
	Amount         string `json:"amount"`
}

func (q *Queries) CreateDeposit(ctx context.Context, arg CreateDepositParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createDeposit, arg.IdempotencyKey, arg.AccountID, arg.Amount)
}

const getDeposit = `-- name: GetDeposit :one
SELECT id, idempotency_key, account_id, amount, status, tx_hash, confirmations, retry_count, error_message, created_at, updated_at FROM deposits WHERE id = ? LIMIT 1
`

func (q *Queries) GetDeposit(ctx context.Context, id uint64) (Deposit, error) {
	row := q.db.QueryRowContext(ctx, getDeposit, id)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.AccountID,
		&i.Amount,
		&i.Status,
		&i.TxHash,
		&i.Confirmations,
		&i.RetryCount,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDepositByIdempotencyKey = `-- name: GetDepositByIdempotencyKey :one
SELECT id, idempotency_key, account_id, amount, status, tx_hash, confirmations, retry_count, error_message, created_at, updated_at FROM deposits WHERE idempotency_key = ? LIMIT 1
`

func (q *Queries) GetDepositByIdempotencyKey(ctx context.Context, idempotencyKey string) (Deposit, error) {
	row := q.db.QueryRowContext(ctx, getDepositByIdempotencyKey, idempotencyKey)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.AccountID,
		&i.Amount,
		&i.Status,
		&i.TxHash,
		&i.Confirmations,
		&i.RetryCount,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementDepositRetry = `-- name: IncrementDepositRetry :exec
UPDATE deposits SET retry_count = retry_count + 1 WHERE id = ?
`

func (q *Queries) IncrementDepositRetry(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, incrementDepositRetry, id)
	return err
}

const listDepositsByStatus = `-- name: ListDepositsByStatus :many
SELECT id, idempotency_key, account_id, amount, status, tx_hash, confirmations, retry_count, error_message, created_at, updated_at FROM deposits WHERE status = ? ORDER BY created_at LIMIT ?
`

type ListDepositsByStatusParams struct {
	Status DepositsStatus `json:"status"`
	Limit  int32          `json:"limit"`
}

func (q *Queries) ListDepositsByStatus(ctx context.Context, arg ListDepositsByStatusParams) ([]Deposit, error) {
	rows, err := q.db.QueryContext(ctx, listDepositsByStatus, arg.Status, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deposit{}
	for rows.Next() {
		var i Deposit
		if err := rows.Scan(
			&i.ID,
			&i.IdempotencyKey,
			&i.AccountID,
			&i.Amount,
			&i.Status,
			&i.TxHash,
			&i.Confirmations,
			&i.RetryCount,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDepositStatus = `-- name: UpdateDepositStatus :exec
UPDATE deposits
SET status = ?, tx_hash = ?, confirmations = ?, error_message = ?, retry_count = ?
WHERE id = ?
`

type UpdateDepositStatusParams struct {
	Status        DepositsStatus `json:"status"`
	TxHash        sql.NullString `json:"tx_hash"`
	Confirmations sql.NullInt32  `json:"confirmations"`
	ErrorMessage  sql.NullString `json:"error_message"`
	RetryCount    sql.NullInt32  `json:"retry_count"`
	ID            uint64         `json:"id"`
}

func (q *Queries) UpdateDepositStatus(ctx context.Context, arg UpdateDepositStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateDepositStatus,
		arg.Status,
		arg.TxHash,
		arg.Confirmations,
		arg.ErrorMessage,
		arg.RetryCount,
		arg.ID,
	)
	return err
}
