// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product.sql

package db

import (
	"context"
	"database/sql"
)

const createProduct = `-- name: CreateProduct :execresult
INSERT INTO products (sku, name, price, status)
VALUES (?, ?, ?, ?)
`

type CreateProductParams struct {
	Sku    string         `json:"sku"`
	Name   string         `json:"name"`
	Price  string         `json:"price"`
	Status ProductsStatus `json:"status"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createProduct,
		arg.Sku,
		arg.Name,
		arg.Price,
		arg.Status,
	)
}

const deleteProduct = `-- name: DeleteProduct :exec
UPDATE products SET status = 'INACTIVE' WHERE id = ?
`

func (q *Queries) DeleteProduct(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, deleteProduct, id)
	return err
}

const getProduct = `-- name: GetProduct :one
SELECT id, sku, name, price, status, created_at, updated_at FROM products WHERE id = ? LIMIT 1
`

func (q *Queries) GetProduct(ctx context.Context, id uint64) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Price,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductBySKU = `-- name: GetProductBySKU :one
SELECT id, sku, name, price, status, created_at, updated_at FROM products WHERE sku = ? LIMIT 1
`

func (q *Queries) GetProductBySKU(ctx context.Context, sku string) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductBySKU, sku)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Price,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, sku, name, price, status, created_at, updated_at FROM products
WHERE status = COALESCE(?, status)
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListProductsParams struct {
	Status NullProductsStatus `json:"status"`
	Limit  int32              `json:"limit"`
	Offset int32              `json:"offset"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProducts, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Sku,
			&i.Name,
			&i.Price,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE products
SET name = ?, price = ?, status = ?
WHERE id = ?
`

type UpdateProductParams struct {
	Name   string         `json:"name"`
	Price  string         `json:"price"`
	Status ProductsStatus `json:"status"`
	ID     uint64         `json:"id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.db.ExecContext(ctx, updateProduct,
		arg.Name,
		arg.Price,
		arg.Status,
		arg.ID,
	)
	return err
}
