// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateProduct(ctx context.Context, arg CreateProductParams) (sql.Result, error)
	DeleteProduct(ctx context.Context, id uint64) error
	GetProduct(ctx context.Context, id uint64) (Product, error)
	GetProductBySKU(ctx context.Context, sku string) (Product, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) error
}

var _ Querier = (*Queries)(nil)
