// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"
	"database/sql"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) as total FROM users
WHERE status != 'DELETED'
  AND (? IS NULL OR role = ?)
  AND (? IS NULL OR kyc_status = ?)
`

type CountUsersParams struct {
	Role      NullUsersRole      `json:"role"`
	KycStatus NullUsersKycStatus `json:"kyc_status"`
}

// 사용자 수 조회 (페이징용)
func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers,
		arg.Role,
		arg.Role,
		arg.KycStatus,
		arg.KycStatus,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createUser = `-- name: CreateUser :execresult

INSERT INTO users (email, external_id, name, phone, role, status)
VALUES (?, ?, ?, ?, ?, 'ACTIVE')
`

type CreateUserParams struct {
	Email      string         `json:"email"`
	ExternalID sql.NullString `json:"external_id"`
	Name       string         `json:"name"`
	Phone      sql.NullString `json:"phone"`
	Role       UsersRole      `json:"role"`
}

// ============================================================================
// User Queries - Phase 1
// ============================================================================
// 사용자 생성 (external_id는 서비스 레이어에서 UUID 생성 후 전달)
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser,
		arg.Email,
		arg.ExternalID,
		arg.Name,
		arg.Phone,
		arg.Role,
	)
}

const existsUserByEmail = `-- name: ExistsUserByEmail :one
SELECT EXISTS(
    SELECT 1 FROM users WHERE email = ? AND status != 'DELETED'
) as exists_flag
`

// 이메일 중복 체크
func (q *Queries) ExistsUserByEmail(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsUserByEmail, email)
	var exists_flag bool
	err := row.Scan(&exists_flag)
	return exists_flag, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, external_id, name, phone, role, kyc_status, kyc_verified_at, status, created_at, updated_at FROM users
WHERE email = ? AND status != 'DELETED'
`

// 이메일로 조회 (중복 체크, 로그인 등)
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.ExternalID,
		&i.Name,
		&i.Phone,
		&i.Role,
		&i.KycStatus,
		&i.KycVerifiedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByExternalID = `-- name: GetUserByExternalID :one
SELECT id, email, external_id, name, phone, role, kyc_status, kyc_verified_at, status, created_at, updated_at FROM users
WHERE external_id = ? AND status != 'DELETED'
`

// 외부 식별자로 조회 (API 노출용, DELETED 제외)
func (q *Queries) GetUserByExternalID(ctx context.Context, externalID sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByExternalID, externalID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.ExternalID,
		&i.Name,
		&i.Phone,
		&i.Role,
		&i.KycStatus,
		&i.KycVerifiedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByExternalIDIncludeDeleted = `-- name: GetUserByExternalIDIncludeDeleted :one
SELECT id, email, external_id, name, phone, role, kyc_status, kyc_verified_at, status, created_at, updated_at FROM users
WHERE external_id = ?
`

// 내부 상태 전이 검증용 (DELETED 포함)
// 멱등성 보장 및 상태 전이 체크에 사용
func (q *Queries) GetUserByExternalIDIncludeDeleted(ctx context.Context, externalID sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByExternalIDIncludeDeleted, externalID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.ExternalID,
		&i.Name,
		&i.Phone,
		&i.Role,
		&i.KycStatus,
		&i.KycVerifiedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, external_id, name, phone, role, kyc_status, kyc_verified_at, status, created_at, updated_at FROM users
WHERE id = ? AND status != 'DELETED'
`

// 소프트 삭제된 사용자 제외
func (q *Queries) GetUserByID(ctx context.Context, id uint64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.ExternalID,
		&i.Name,
		&i.Phone,
		&i.Role,
		&i.KycStatus,
		&i.KycVerifiedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserForUpdate = `-- name: GetUserForUpdate :one
SELECT id, email, external_id, name, phone, role, kyc_status, kyc_verified_at, status, created_at, updated_at FROM users
WHERE id = ? AND status != 'DELETED'
FOR UPDATE
`

// 트랜잭션 내 row-lock (Primary 지갑 설정, 상태 변경 등 동시성 제어)
func (q *Queries) GetUserForUpdate(ctx context.Context, id uint64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserForUpdate, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.ExternalID,
		&i.Name,
		&i.Phone,
		&i.Role,
		&i.KycStatus,
		&i.KycVerifiedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many

SELECT id, email, external_id, name, phone, role, kyc_status, kyc_verified_at, status, created_at, updated_at FROM users
WHERE status != 'DELETED'
  AND (? IS NULL OR role = ?)
  AND (? IS NULL OR kyc_status = ?)
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListUsersParams struct {
	Role      NullUsersRole      `json:"role"`
	KycStatus NullUsersKycStatus `json:"kyc_status"`
	Limit     int32              `json:"limit"`
	Offset    int32              `json:"offset"`
}

// ============================================================================
// 목록 조회
// ============================================================================
// 사용자 목록 조회 (상태 필터 옵션, 페이징)
func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers,
		arg.Role,
		arg.Role,
		arg.KycStatus,
		arg.KycStatus,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.ExternalID,
			&i.Name,
			&i.Phone,
			&i.Role,
			&i.KycStatus,
			&i.KycVerifiedAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserKycToPending = `-- name: UpdateUserKycToPending :exec

UPDATE users
SET kyc_status = 'PENDING', updated_at = NOW()
WHERE id = ? AND status != 'DELETED'
`

// ============================================================================
// KYC 상태 변경 쿼리 (상태별 분리)
// ============================================================================
// KYC 심사 요청 (NONE/REJECTED → PENDING)
func (q *Queries) UpdateUserKycToPending(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, updateUserKycToPending, id)
	return err
}

const updateUserKycToRejected = `-- name: UpdateUserKycToRejected :exec
UPDATE users
SET kyc_status = 'REJECTED', updated_at = NOW()
WHERE id = ? AND status != 'DELETED'
`

// KYC 거절 (PENDING → REJECTED)
func (q *Queries) UpdateUserKycToRejected(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, updateUserKycToRejected, id)
	return err
}

const updateUserKycToVerified = `-- name: UpdateUserKycToVerified :exec
UPDATE users
SET kyc_status = 'VERIFIED',
    kyc_verified_at = COALESCE(kyc_verified_at, NOW()),
    updated_at = NOW()
WHERE id = ? AND status != 'DELETED'
`

// KYC 승인 (PENDING → VERIFIED, kyc_verified_at 최초 설정 시만)
func (q *Queries) UpdateUserKycToVerified(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, updateUserKycToVerified, id)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE users
SET name = ?, phone = ?, updated_at = NOW()
WHERE id = ? AND status != 'DELETED'
`

type UpdateUserProfileParams struct {
	Name  string         `json:"name"`
	Phone sql.NullString `json:"phone"`
	ID    uint64         `json:"id"`
}

// 프로필 정보 업데이트 (이름, 전화번호)
func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateUserProfile, arg.Name, arg.Phone, arg.ID)
	return err
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE users
SET role = ?, updated_at = NOW()
WHERE id = ? AND status != 'DELETED'
`

type UpdateUserRoleParams struct {
	Role UsersRole `json:"role"`
	ID   uint64    `json:"id"`
}

// 역할 변경 (BUYER, SELLER, BOTH, ADMIN)
func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.ExecContext(ctx, updateUserRole, arg.Role, arg.ID)
	return err
}

const updateUserStatusToActive = `-- name: UpdateUserStatusToActive :execresult
UPDATE users
SET status = 'ACTIVE', updated_at = NOW()
WHERE id = ? AND status = 'SUSPENDED'
`

// 정지 해제 (SUSPENDED → ACTIVE only, DELETED 복구 불가)
func (q *Queries) UpdateUserStatusToActive(ctx context.Context, id uint64) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUserStatusToActive, id)
}

const updateUserStatusToDeleted = `-- name: UpdateUserStatusToDeleted :execresult
UPDATE users
SET status = 'DELETED', updated_at = NOW()
WHERE id = ? AND status != 'DELETED'
`

// 소프트 삭제 (복구 불가, 단방향 전이)
func (q *Queries) UpdateUserStatusToDeleted(ctx context.Context, id uint64) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUserStatusToDeleted, id)
}

const updateUserStatusToSuspended = `-- name: UpdateUserStatusToSuspended :execresult

UPDATE users
SET status = 'SUSPENDED', updated_at = NOW()
WHERE id = ? AND status = 'ACTIVE'
`

// ============================================================================
// 사용자 상태 변경 (:execresult로 RowsAffected 검증 가능)
// ============================================================================
// 사용자 정지 (ACTIVE → SUSPENDED)
func (q *Queries) UpdateUserStatusToSuspended(ctx context.Context, id uint64) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUserStatusToSuspended, id)
}
