// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@example.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/users": {
            "get": {
                "description": "Get paginated list of users with optional filters",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "List users",
                "parameters": [
                    {
                        "enum": [
                            "BUYER",
                            "SELLER",
                            "BOTH",
                            "ADMIN"
                        ],
                        "type": "string",
                        "description": "Filter by role",
                        "name": "role",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "NONE",
                            "PENDING",
                            "VERIFIED",
                            "REJECTED"
                        ],
                        "type": "string",
                        "description": "Filter by KYC status",
                        "name": "kyc_status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Page size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User list",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_user.ListUsersResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid query parameters",
                        "schema": {
                            "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Register a new user with email, name, and role. An account is automatically created.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Create a new user",
                "parameters": [
                    {
                        "description": "User registration data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_user.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "User created successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_user.UserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Email already registered",
                        "schema": {
                            "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/users/{id}": {
            "get": {
                "description": "Retrieve user details by external ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get user by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User external ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User details",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_user.UserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update user's name and phone number",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Update user profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User external ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Profile update data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_user.UpdateUserProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Updated user",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_user.UserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Soft-delete a user (irreversible)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Delete user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User external ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "User deleted"
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/users/{id}/activate": {
            "post": {
                "description": "Reactivate a suspended user (SUSPENDED -\u003e ACTIVE)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Activate user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User external ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Activated user",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_user.UserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid state transition (deleted users cannot be reactivated)",
                        "schema": {
                            "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/users/{id}/kyc/approve": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Approve user's KYC verification (PENDING -\u003e VERIFIED) - Admin only",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Approve KYC",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User external ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "KYC approved",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_user.UserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid state transition",
                        "schema": {
                            "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/users/{id}/kyc/reject": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Reject user's KYC verification (PENDING -\u003e REJECTED) - Admin only",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Reject KYC",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User external ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "KYC rejected",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_user.UserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid state transition",
                        "schema": {
                            "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/users/{id}/kyc/request": {
            "post": {
                "description": "Request KYC verification for the user (NONE/REJECTED -\u003e PENDING)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Request KYC verification",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User external ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "KYC requested",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_user.UserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid state transition",
                        "schema": {
                            "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/users/{id}/role": {
            "put": {
                "description": "Change user's role (BUYER, SELLER, BOTH)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Update user role",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User external ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Role update data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_user.UpdateUserRoleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Updated user",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_user.UserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Cannot assign ADMIN role",
                        "schema": {
                            "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/users/{id}/suspend": {
            "post": {
                "description": "Suspend an active user (ACTIVE -\u003e SUSPENDED)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Suspend user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User external ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Suspended user",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_user.UserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid state transition",
                        "schema": {
                            "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/users/{id}/wallets": {
            "get": {
                "description": "Get all wallets for a user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wallets"
                ],
                "summary": "List user wallets",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User external ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Wallet list",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_wallet.ListWalletsResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid UUID format",
                        "schema": {
                            "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Register a new Ethereum wallet for the user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wallets"
                ],
                "summary": "Register a new wallet",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User external ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Wallet registration data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_wallet.RegisterWalletRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Wallet created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_wallet.WalletResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Wallet address already registered",
                        "schema": {
                            "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/users/{id}/wallets/{walletId}": {
            "get": {
                "description": "Retrieve wallet details by external ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wallets"
                ],
                "summary": "Get wallet by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User external ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Wallet external ID (UUID)",
                        "name": "walletId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Wallet details",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_wallet.WalletResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid UUID format",
                        "schema": {
                            "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Wallet not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a non-primary wallet (hard delete)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wallets"
                ],
                "summary": "Delete wallet",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User external ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Wallet external ID (UUID)",
                        "name": "walletId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Wallet deleted"
                    },
                    "400": {
                        "description": "Cannot delete primary wallet",
                        "schema": {
                            "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Wallet not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/users/{id}/wallets/{walletId}/label": {
            "put": {
                "description": "Update the label of a wallet",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wallets"
                ],
                "summary": "Update wallet label",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User external ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Wallet external ID (UUID)",
                        "name": "walletId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Label update data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_wallet.UpdateLabelRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Updated wallet",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_wallet.WalletResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Wallet not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/users/{id}/wallets/{walletId}/set-primary": {
            "post": {
                "description": "Set a verified wallet as the primary wallet",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wallets"
                ],
                "summary": "Set wallet as primary",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User external ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Wallet external ID (UUID)",
                        "name": "walletId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Primary wallet",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_wallet.WalletResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Wallet not verified",
                        "schema": {
                            "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Wallet not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/users/{id}/wallets/{walletId}/verify": {
            "post": {
                "description": "Verify wallet ownership using EIP-712 signature",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wallets"
                ],
                "summary": "Verify wallet ownership",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User external ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Wallet external ID (UUID)",
                        "name": "walletId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Signature and message data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_wallet.VerifyWalletRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Verified wallet",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_wallet.WalletResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid signature or verification failed",
                        "schema": {
                            "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Wallet not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns server health status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_common_handler.HealthResponse"
                        }
                    }
                }
            }
        },
        "/ready": {
            "get": {
                "description": "Returns server readiness status including DB and Redis connectivity",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Readiness check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_common_handler.ReadyResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/internal_common_handler.ReadyResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.ErrorBody": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "details": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                }
            }
        },
        "github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.ErrorBody"
                }
            }
        },
        "github_com_ahwlsqja_StableCoin-B2B-Commerce-Settlement-Engine_internal_common_middleware.SuccessResponse": {
            "type": "object",
            "properties": {
                "data": {}
            }
        },
        "internal_common_handler.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "internal_common_handler.ReadyResponse": {
            "type": "object",
            "properties": {
                "db": {
                    "type": "string",
                    "example": "ok"
                },
                "redis": {
                    "type": "string",
                    "example": "ok"
                },
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "internal_user.CreateUserRequest": {
            "type": "object",
            "required": [
                "email",
                "name",
                "role"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2,
                    "example": "John Doe"
                },
                "phone": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 10,
                    "example": "010-1234-5678"
                },
                "role": {
                    "type": "string",
                    "enum": [
                        "BUYER",
                        "SELLER",
                        "BOTH"
                    ],
                    "example": "BUYER"
                }
            }
        },
        "internal_user.ListUsersResponse": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                },
                "users": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_user.UserResponse"
                    }
                }
            }
        },
        "internal_user.UpdateUserProfileRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2,
                    "example": "John Doe"
                },
                "phone": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 10,
                    "example": "010-1234-5678"
                }
            }
        },
        "internal_user.UpdateUserRoleRequest": {
            "type": "object",
            "required": [
                "role"
            ],
            "properties": {
                "role": {
                    "type": "string",
                    "enum": [
                        "BUYER",
                        "SELLER",
                        "BOTH"
                    ],
                    "example": "SELLER"
                }
            }
        },
        "internal_user.UserResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "id": {
                    "type": "string",
                    "example": "usr_abc123def456"
                },
                "kyc_status": {
                    "type": "string",
                    "example": "NONE"
                },
                "kyc_verified_at": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "example": "John Doe"
                },
                "phone": {
                    "type": "string",
                    "example": "010-1234-5678"
                },
                "role": {
                    "type": "string",
                    "example": "BUYER"
                },
                "status": {
                    "type": "string",
                    "example": "ACTIVE"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "internal_wallet.ListWalletsResponse": {
            "type": "object",
            "properties": {
                "total": {
                    "type": "integer"
                },
                "wallets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_wallet.WalletResponse"
                    }
                }
            }
        },
        "internal_wallet.RegisterWalletRequest": {
            "type": "object",
            "required": [
                "address"
            ],
            "properties": {
                "address": {
                    "type": "string",
                    "example": "0x742d35Cc6634C0532925a3b844Bc454e4438f44e"
                },
                "label": {
                    "type": "string",
                    "maxLength": 50,
                    "example": "My Main Wallet"
                }
            }
        },
        "internal_wallet.UpdateLabelRequest": {
            "type": "object",
            "required": [
                "label"
            ],
            "properties": {
                "label": {
                    "type": "string",
                    "maxLength": 50,
                    "example": "Trading Wallet"
                }
            }
        },
        "internal_wallet.VerifyWalletRequest": {
            "type": "object",
            "required": [
                "message",
                "signature"
            ],
            "properties": {
                "message": {
                    "$ref": "#/definitions/internal_wallet.VerifyWalletRequestMessage"
                },
                "signature": {
                    "description": "Signature: 0x prefix + 130 hex chars (65 bytes)",
                    "type": "string",
                    "example": "0x1234...abcd"
                }
            }
        },
        "internal_wallet.VerifyWalletRequestMessage": {
            "type": "object",
            "required": [
                "nonce",
                "timestamp"
            ],
            "properties": {
                "nonce": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 8,
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "timestamp": {
                    "type": "integer",
                    "example": 1706000000
                }
            }
        },
        "internal_wallet.WalletResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "0x742d35cc6634c0532925a3b844bc454e4438f44e"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "is_primary": {
                    "type": "boolean",
                    "example": false
                },
                "is_verified": {
                    "type": "boolean",
                    "example": false
                },
                "label": {
                    "type": "string",
                    "example": "My Main Wallet"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "X-API-Key",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "B2B Commerce Settlement Engine API",
	Description:      "재고관리 + 주문처리 + 스테이블코인 정산 API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
